version: '3'
services:
  # MongoDB
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: fulll
      MONGO_INITDB_ROOT_PASSWORD: fulll
    ports:
      - "27017:27017"
    volumes:
      - ./infra/mongo:/data/db

  # Admin MongoDB
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fulll
      ME_CONFIG_MONGODB_ADMINPASSWORD: fulll
      ME_CONFIG_MONGODB_URL: mongodb://fulll:fulll@mongo:27017/
